version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js"
      - aws --version
      - which python
      - python -v
      - n 18
      - npm -v  
  build:
    commands:
      - echo "Build commands go here"
