version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js"
      - aws --version
      - n 18
      - npm -v  
      - npm install -g aws-cdk
      - cdk --version  
  build:
    commands:
      - echo "Build commands go here"
