version: 0.2

phases:
  install:
    commands:
      - source .venv/bin/activate
      - python -m pip install -r requirements.txt  
  build:
    commands:
      - cdk synth
artifacts:
  files:
    - '**/*'
